#https://gist.github.com/maxkostinevich/9672966565aeb749d41e49673be4e7fa ///
#https://github.com/colbyfayock/my-static-website
#https://www.freecodecamp.org/news/how-to-use-github-actions-to-deploy-a-next-js-website-to-aws-s3/
#Deploy to S3
name: Deploy packages/frontend-kds on master branch
on:
  push:
    paths:
      - "schema.prisma"
      - "package.json"
      - "packages/frontend-kds/**"
      - "packages/db/**"
      - ".github/workflows/deployment-frontend-kds.yaml"
    branches:
      - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create env file Frontend
        run: |
          echo "SKIP_PREFLIGHT_CHECK=true" >> ./packages/frontend-kds/.env && cat ./packages/frontend-kds/.env &&
          echo "REACT_APP_API_URL=https://07exn8iymg.execute-api.ap-southeast-1.amazonaws.com/prod" >> ./packages/frontend-kds/.env && cat ./packages/frontend-kds/.env &&
          echo "REACT_APP_WEBSOCKET_URL=wss://jot2avoikk.execute-api.ap-southeast-1.amazonaws.com/prod" >> ./packages/frontend-kds/.env && cat ./packages/frontend-kds/.env &&
          echo "SKIP_PREFLIGHT_CHECK=true" >> ./packages/db/.env && cat ./packages/db/.env
      - name: Install Node
        run: npm install && npm run bootstrap
      - name: Build Base Module
        run: cd packages/db && npm run build && cd ../util && npm run build
      - name: Build
        run: cd ./packages/frontend-kds/ && npm run build
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Deploy
        run: aws s3 sync ./packages/frontend-kds/build s3://${{ secrets.KDS_S3_BUCKET }}
